// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "placeholder",
        "contact": {
            "name": "Max",
            "url": "xamma.github.io",
            "email": "xam93@live.de"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pokemon": {
            "put": {
                "description": "Updates a Pokemon in the Pokedex by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Update Pokemon by name",
                "parameters": [
                    {
                        "description": "Pokemon object",
                        "name": "pokemon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Pokemon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Failed to update Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to update Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a Pokemon to the Pokedex",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Add Pokemon",
                "parameters": [
                    {
                        "description": "Pokemon object",
                        "name": "pokemon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Pokemon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pokemon created successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pokemon/{id}": {
            "put": {
                "description": "Updates a Pokemon in the Pokedex by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Update Pokemon by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pokemon ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Pokemon object",
                        "name": "pokemon",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Pokemon"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Failed to update Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to update Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pokemon/{name}": {
            "get": {
                "description": "Gets a Pokemon from the Pokedex by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Get Pokemon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pokemon name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pokemon"
                        }
                    },
                    "404": {
                        "description": "Pokemon not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve Pokemon record",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a Pokemon from the Pokedex by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Deletes Pokemon",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pokemon name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to delete Pokemon",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/pokemons": {
            "get": {
                "description": "Gets all pokemons from the pokedex.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pokedex"
                ],
                "summary": "Get Pokemons.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Pokemon": {
            "type": "object",
            "properties": {
                "caught_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gokedex",
	Description:      "Gokedex RestAPI with PostgreSQL.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
